parameters:
# nothing to declare

services:
  _defaults:
    autowire: true

  LeoVie\PhpParamGenerator\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/PhpParamGeneratorBundle.php'

  _instanceof:
    LeoVie\PhpParamGenerator\ParamGenerator\ParamGenerator:
      tags: [ 'app.param_generator' ]
  LeoVie\PhpParamGenerator\ParamGenerator\ParamGeneratorFinder:
    arguments: [ !tagged_iterator { tag: 'app.param_generator' } ]
    public: true