parameters:
# nothing to declare

services:
  _defaults:
    autowire: true

  LeoVie\PhpParamGenerator\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/PhpParamGeneratorBundle.php'